### ISSUE TITLE
Improvements for Windows

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/valid-filename#2]
Hey, I'm looking for a module to be used in the browser which can validate filenames for multiple platforms and this seems to be the best fit but I noticed a few things missing for the Windows filename rules. The full story is available on [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#Naming_Conventions). Particularly:
- `\u0000` to `\u0031` are not allowed.
- The names CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9 are not allowed.

I'd propose a optional `platform` argument so one can target multiple platforms.

There's a few more subtle details like `MAX_PATH` restrictions. I'd also suggest removing the current 256 char limit, as it is no longer valid for recent Windows 10 versions, and it's really just a wild guess imho as one cannot know the true limit without knowing the file's full (resolved) path.

**Comment by sindresorhus** [comment]
👍 Sounds good.

**Comment by silverwind** [comment]
To be even more accurate one could replace `platform` with `filesystem` option as different file systems have different file name rules and it'd be quite inacurrate to assume a `ext` variant on Linux, for example.

But I wouldn't even know how to get the file system type in Node.js, for example.

**Comment by sindresorhus** [comment]
Hmm, yeah, been thinking about it and not sure if a `platform` option makes sense. I'd argue you should adhere to the lowest common denominator, for consistency and portability between platforms.

**Comment by silverwind** [comment]
I think we can support both. If `filesystem` is given, use that else use the most common file system for the `platform`. Default will be the `win32/ntfs` behaviour for portability. Also, filesystem stuff will take a bit of time to research, I'll start with the default file systems now.

**Comment by sindresorhus** [comment]
@silverwind Just curious, what is your use-case where using win32/ntfs rules for everything wouldn't work?

**Comment by silverwind** [comment]
Creating files on a Linux server for example. It seems most correct to not restrict the filenames based on rules of another platform. But as you said, it's probably best for portability to enforce a common denominator like the `win32` rules, so it's not set in stone if I go that route.

**Comment by silverwind** [comment]
By the way, would you include `:` on macOS/HFS+? If you save a file in the CLI with `:` in the name, Finder will replace all occurences of `:` with `/`.

**Comment by sindresorhus** [comment]
`:` should not be allowed on HFS+.

**Comment by silverwind** [comment]
Okay, for portability's sake, I'll just extend the regex with the non-printable characters `\x00-\x1F` and then add the reserved filenames to this module.

**Comment by sindresorhus** [comment]
Note to self: Also add those characters to https://github.com/sindresorhus/filenamify
