### ISSUE TITLE
`.` and `..`

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/valid-filename#4]
Totally forgot about them. How should we handle them? I think they're only invalid on Unix.

**Comment by sindresorhus** [comment]
I think we should disallow them. I'm already removing them in `filenamify`: https://github.com/sindresorhus/filenamify/blob/c7e7fa9e46a99330cf7643928d1bd93f4e5a2f46/index.js#L11

**Comment by silverwind** [comment]
Through another regex (`/^\.+$/`) or in this module?

**Comment by sindresorhus** [comment]
Just in this module.

**Comment by sindresorhus** [comment]
Note that the regex is `/^\.+/`, not `/^\.+$/`.

**Comment by silverwind** [comment]
Okay. Seems like `...` is actually valid, so I'll go with `/^\.\.?$/`.

**Comment by sindresorhus** [comment]
That that only matches filenames named `.` or `..`. The intention is to match filenames _starting with_ `.` or `..`.

**Comment by silverwind** [comment]
That's the intention. `...` and `..anything` are still valid filenames.

**Comment by silverwind** [comment]
If you'd match for a starting `.`, you'd exclude all dotfiles 😉

**Comment by sindresorhus** [comment]
Ah, right. I was thinking of filenames like `../`, but `/` is already a reserved character, so doesn't matter.

**Comment by sindresorhus** [comment]
I did a patch release. It's the 5 second rules for semver :p

**Comment by silverwind** [comment]
Ha, I almost entered `np major` :)
