### ISSUE TITLE
Add type definitions

### ISSUE THREAD

**Issue by kittaakos** [sindresorhus/valid-filename#5]
Having type definitions would be nice; do you accept PRs? Thanks!

**Comment by SamVerschueren** [comment]
Sorry, it's better to publish them to DefinitelyTyped https://github.com/sindresorhus/ama/issues/439

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
